import Head from 'next/head';
import React, { useState } from 'react';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import Box from '@material-ui/core/Box';
import Dashboard from '../components/Dashboard';
import QuestionModal from '../components/QuestionModal';
import Stepper from '../components/Stepper';
import {
  Typography,
  Button,
  TextField,
  InputAdornment,
  Container,
  Grid,
} from '@material-ui/core'; // Importing from Material-UI v4

import Final from '../components/Final';

export default function Generate() {
  return (
    <>
      <Head>
        <title>Sky Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="md">
          <Dashboard />
          <Stepper />
        </Container>
      </main>
    </>
  );
}
