import Head from 'next/head';
import React, { useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Box from '@material-ui/core/Box';

import BizProblem from '../components/BizProblem';
import Dashboard from '../components/Dashboard';

import axios from 'axios';

import {
  Typography,
  Button,
  TextField,
  InputAdornment,
  Container,
  Grid,
} from '@material-ui/core'; // Importing from Material-UI v4

export default function Home() {
  const backendUrl = 'http://localhost:5000';
  const [bizProb, setPrompt] = useState('');
  const [questions, setQuestions] = useState();

  return (
    <>
      <Head>
        <title>Sky Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="sm">
          <Dashboard />
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
            }}
          >
            <Grid container spacing={2}>
              <Grid item xs={12}>
                <Typography variant="h4" align="center">
                  Let's Build something cool today!
                </Typography>
              </Grid>
              <Grid item xs={12}>
                <BizProblem />
              </Grid>
            </Grid>
          </div>
        </Container>
      </main>
    </>
  );
}
