import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Box from '@material-ui/core/Box';

import BizProblem from '../components/BizProblem';
import Dashboard from '../components/Dashboard';

import axios from 'axios';

import {
  Typography,
  Button,
  TextField,
  InputAdornment,
  Container,
  Grid,
} from '@material-ui/core'; // Importing from Material-UI v4
import { useAppDispatch, useAppSelector } from '../redux/hooks';
import {
  updateQuestions,
  updateBizProblem,
} from '../redux/slices/activeEntities';

export default function Home() {
  const questionsNew = useAppSelector(
    (state) => state.activeEntities.questions
  );

  const bizProblemNew = useAppSelector(
    (state) => state.activeEntities.bizProblem
  );

  const dispatch = useAppDispatch();


  return (
    <>
      <Head>
        <title>Cloud Pilot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="sm">
          <Dashboard />
          <div
            style={{
              height: '80vh',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <Grid container spacing={2}>
              <Grid item xs={12}>
                <Typography variant="h4" align="center">
                  Let's Build something cool today!
                </Typography>
              </Grid>
              <Grid item xs={12}>
                <BizProblem />
              </Grid>
            </Grid>
          </div>
        </Container>
      </main>
    </>
  );
}
